remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Edoardo Vacchi
  tagline: |
    Programming Language Nerd 
    Kogito @ Red Hat

  date_format: "%b %-d, %Y"

  social_links:
    twitter: evacchi
    github: evacchi
    linkedIn: in/edoardovacchi 

show_excerpts: true

#  navigation:
#    - title: My Work
#      url: "/my-work"
#    - title: Resume
#      url: "/resume"

