remote_theme: thelehhman/plainwhite-jekyll
title: |
  Middle of Nowhere  
plainwhite:
  name: Middle of Nowhere
  tagline: |
    Edoardo Vacchi
    Programming Language Nerd 
    Kogito @ Red Hat

  date_format: "%b %-d, %Y"

  social_links:
    twitter: evacchi
    github: evacchi
    linkedIn: in/edoardovacchi 

show_excerpts: false

#  navigation:
#    - title: My Work
#      url: "/my-work"
#    - title: Resume
#      url: "/resume"

