remote_theme: thelehhman/plainwhite-jekyll
title: |
  Middle of Nowhere  
plainwhite:
  name: Middle of Nowhere
  tagline: |
    Edoardo Vacchi
    Programming Language Nerd 
    Kogito @ Red Hat
  portfolio_image: "assets/portfolio.png"
  date_format: "%b %-d, %Y"

  social_links:
    twitter: evacchi
    github: evacchi
    linkedIn: in/edoardovacchi 

  navigation:
    - title: About Me
      url: "/about/"


include: ['_pages']

show_excerpts: false
plugins:
- jekyll-seo-tag

